version: "3.8"
services:
    php:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION:-8.1}
        volumes:
            - .:/form
